dist: xenial
addons:
  apt:
    packages:
      - openscad
language: python
python:
  - "2.7"
install:
  - pip install -U platformio
sudo: false
cache:
  directories:
    - "~/.platformio"
script:
  - make --always-make
